### ISSUE TITLE
Static Analysis Engine for the New Syntax

### ISSUE THREAD

**Issue by kustosz** [luna/enso#91]
### Summary
Once the new syntax parser lands on master, we should start using it. This task is about creating a translation layer between the parser data structures and Truffle nodes, including migrating the tiny bits of static analysis we were doing.

### Specification

- Establish a set of more discrete tasks such that the project plan can be effectively managed.

### Acceptance Criteria & Test Cases

- New, smaller tasks have been created to track the details of this work.

**Comment by kustosz** [comment]
Due to the nature of our caches, the static analysis engine should desugar chains of single-argument functions into multiple-argument functions. I.e. `x -> y -> z` should become `x y -> z`.

**Comment by iamrecursion** [comment]
The static analysis framework will be implemented as a set of passes that run on the source AST and finish by spitting out the AST executed by the Enso interpreter. In between the start and finish will be a number of 'Phases', each of which will contain one or more 'Passes'. Key elements of the design are as follows:

- The system supports programmer-declaration of a set of `Phase`s, each of which contains one or more `Pass`es. 
- Phases may depend on phases, and passes must depend on at least one other pass. If a given entity depends on another entity (e.g. the pass `lowering.CPS` depends on the phase `Desugar`), then the dependencies must be run ahead of the dependents.
- The dependency graph between passes and phases should provide a compile-time known total-ordering of passes.
- Certain passes may be _enabled_ and _disabled_ (see below), but the order of the passes is fixed at compile time. 
- Disabling a pass depended on by others should disable the passes that depend on it, further maintaining semantic correctness. 
- It must be possible to create 'aggregate passes' that enable or disable multiple passes at once.

The code will be written in Scala in order to provide type-system-level correct-by-construction pass orderings. It must be impossible to construct an ordering of passes that violates the dependencies between phases and passes. 

In addition to the basic functionality, the pass structure is required to be runtime configurable (to an extent). While the necessary passes cannot be disabled, some additional default optimisations should be able to be turned off, and there may be _further_ slower optimisations that can be turned on for non-interactive use-cases. This will work as follows:

- Users may provide flags such as `-pass.optimisation.ConstantFold` to disable a pass, or `+pass.optimisation.LateLambdaLift` to enable a pass.
- Pass flags are organised hierarchically based on the code-structure of the passes themselves. Taking the second example above, `pass` indicates the flag type, but `optimisation` pertains to all optimisations made by the static analysis framework.
- The flags can also operate in aggregate (e.g. `+pass.optimisation.NonInteractive`, which would enable a set of passes that increase performance while decreasing interactivity).

**Comment by iamrecursion** [comment]
The roadmap is as follows:

1. Implement the framework.
2. Make the parser do the thing.
3. Without adding any additional static analysis (but migrating existing passes), integrate the new parser.
4. Implement the _additional_ passes that take place as part of the desugaring stage.
5. Work on further optimisations and CPS.

I imagine the phases being stratified as follows:
- **Parsing:** Turning source code into the Source AST.
- **Desugaring:** Converting any syntax sugar into primitive forms, still using the Source AST. This includes all of the desugaring passes mentioned [above](https://github.com/luna/enso/issues/91#issue-482272997). 
- **Typechecking:** Typechecking of Enso code. Tthis will operate on its own structures and may run subsequent phases for the purposes of code execution during typechecking.
- **Lowering:** Conversion of all (or potentially part) of the program into Continuation-Passing Style. This will use its own internal graph representation (the `CPSGraph`).
- **Optimisation:** Transformations from `CPSGraph -> CPSGraph` with the intention of increasing the performance of generated code.
